### ISSUE TITLE
Undefined Variables

### ISSUE THREAD

**Issue by hasnaties** [BaseMax/PHPTinyCms#1]
While opening the TinyCMS folder in the browser. It shows the undefined variable at line 19,20 and 21 in the file of single.php

**Comment by BaseMax** [comment]
Hi, 

Thanks for your report.
This was because you were entering an incorrect ID that did not exist in the database.

> We tried to keep the files simple enough.

I apply a change in the file, Please try again?
https://github.com/BaseMax/PHPTinyCms/commit/2f3cd7c25ffbd9618f692ed806b111db9819f034


Regards,
Max

**Comment by BaseMax** [comment]
Hi,
I did not receive a message from you. So I close this issue temporarily. But if you want to tell something, please write.
